"use client";

import { useState } from "react";
import { BrainCircuit, ChartNoAxesCombined, Code2, Globe2, Palette, Sparkles, Smartphone } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { GlassPanel } from "@/components/ui/GlassPanel";
import { Reveal } from "@/components/ui/Reveal";
import { services } from "@/lib/site-data";

const iconMap: Record<(typeof services)[number]["icon"], LucideIcon> = { brain: BrainCircuit, globe: Globe2, code: Code2, sparkles: Sparkles, smartphone: Smartphone, chart: ChartNoAxesCombined, palette: Palette };

export function ServiceExplorer() {
  const [active, setActive] = useState(services[0].slug);
  const current = services.find((service) => service.slug === active) ?? services[0];
  const Icon = iconMap[current.icon];
  return <section className="bg-surface px-6 py-28 md:px-12 lg:px-20 lg:py-36"><div className="section-shell"><div aria-label="Service categories" className="flex flex-wrap gap-3" role="tablist">{services.map((service) => <button aria-controls={`service-panel-${service.slug}`} aria-selected={active === service.slug} className={active === service.slug ? "rounded-full bg-ink px-5 py-3 text-[0.62rem] font-bold uppercase tracking-[0.16em] text-white" : "rounded-full border border-ink/10 bg-white px-5 py-3 text-[0.62rem] font-bold uppercase tracking-[0.16em] text-muted transition hover:border-violet hover:text-violet"} id={`service-tab-${service.slug}`} key={service.slug} onClick={() => setActive(service.slug)} role="tab" type="button">{service.title.replace(" for decisions ahead.", "").replace("Brand, Interface & Growth Systems", "Brand + growth")}</button>)}</div><div className="mt-12 grid gap-6 lg:grid-cols-[.82fr_1.18fr]"><GlassPanel className="min-h-[27rem] bg-gradient-to-br from-violet to-cyan p-8 text-white md:p-12"><Badge accent="ink" className="border-white/25 bg-white/15 text-white">{current.eyebrow}</Badge><div className="mt-20"><Icon aria-hidden="true" className="size-9" /><h2 className="mt-6 max-w-xl font-display text-4xl font-bold leading-[0.92] tracking-[-0.07em] md:text-6xl">{current.title}</h2><p className="mt-6 max-w-lg text-base leading-8 text-white/75">{current.description}</p><Button className="mt-8" href="/contact" variant="soft">Talk through the system</Button></div></GlassPanel><div aria-live="polite" className="grid gap-4" id={`service-panel-${current.slug}`} role="tabpanel" aria-labelledby={`service-tab-${current.slug}`}><div className="border-b border-ink/10 pb-6"><p className="text-[0.62rem] font-bold uppercase tracking-[0.24em] text-violet">The useful layer</p><h3 className="mt-3 font-display text-3xl font-bold tracking-[-0.06em]">{current.shortDescription}</h3></div>{["Clearer handoffs", "A faster path to trust", "Built for the next release"].map((item, index) => <Reveal delay={index * 0.07} key={item}><GlassPanel className="flex min-h-24 items-center justify-between p-6"><div><span className="text-[0.62rem] font-mono text-muted">0{index + 1}</span><p className="mt-2 font-display text-xl font-bold tracking-[-0.04em]">{item}</p></div><span className="grid size-10 place-items-center rounded-full bg-surface text-violet"><Icon aria-hidden="true" className="size-4" /></span></GlassPanel></Reveal>)}</div></div></div></section>;
}

export function ProcessTimeline() {
  const process = [{ number: "01", title: "Read the friction", copy: "We listen for the constraint under the request." }, { number: "02", title: "Make the shape", copy: "We turn the signal into a clear, testable system." }, { number: "03", title: "Move with intent", copy: "We build, refine, and ship the next useful version." }, { number: "04", title: "Keep the orbit", copy: "We watch the real-world signals and compound what works." }];
  return <section className="bg-white px-6 py-28 md:px-12 lg:px-20 lg:py-36"><div className="section-shell grid gap-16 lg:grid-cols-[.75fr_1.25fr]"><div><Badge accent="cyan">The process</Badge><h2 className="mt-6 font-display text-4xl font-bold tracking-[-0.07em] md:text-6xl">No black box.<br /><span className="text-muted">Just momentum.</span></h2></div><div className="relative">{process.map((item, index) => <Reveal delay={index * 0.08} key={item.number}><div className="relative flex gap-8 border-l border-ink/10 pb-12 pl-8 last:pb-0"><span className="absolute -left-3 top-0 grid size-6 place-items-center rounded-full border border-violet bg-white text-[0.5rem] font-bold text-violet">{item.number}</span><div><p className="text-[0.62rem] uppercase tracking-[0.2em] text-muted">step / {item.number}</p><h3 className="mt-3 font-display text-3xl font-bold tracking-[-0.06em]">{item.title}</h3><p className="mt-3 max-w-md leading-7 text-muted">{item.copy}</p></div></div></Reveal>)}</div></div></section>;
}

export function TechStackGrid() {
  const stack = ["Next.js", "TypeScript", "React", "Three.js", "GSAP", "Lenis", "AI workflows", "Search systems"];
  return <section className="bg-ink px-6 py-28 text-white md:px-12 lg:px-20 lg:py-36"><div className="section-shell"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><Badge accent="cyan">The toolkit</Badge><h2 className="mt-6 font-display text-4xl font-bold tracking-[-0.07em] md:text-6xl">Quietly powerful<br /><span className="text-cyan">under the hood.</span></h2></div><p className="max-w-sm leading-8 text-white/55">A modern stack is useful when it disappears into the experience.</p></div><div className="mt-16 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{stack.map((item, index) => <Reveal delay={index * 0.05} key={item}><GlassPanel dark className="group min-h-32 p-6 transition hover:border-cyan/50 hover:bg-white/10"><span className="text-[0.62rem] font-mono text-cyan">0{index + 1}</span><p className="mt-8 font-display text-2xl font-bold tracking-[-0.05em] transition group-hover:text-cyan">{item}</p></GlassPanel></Reveal>)}</div></div></section>;
}
