"use client";

import dynamic from "next/dynamic";
import { useRef, useState } from "react";
import { Check } from "lucide-react";
import { AnimatePresence, motion, useMotionValueEvent, useScroll } from "framer-motion";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Reveal } from "@/components/ui/Reveal";
import { ProductFallback } from "@/components/three/WebGLFallback";
import { products } from "@/lib/site-data";

const ProductViewer = dynamic(() => import("@/components/three/ProductViewer").then((module) => module.ProductViewer), {
  ssr: false,
  loading: () => <ProductFallback />,
});

export function ProductsHero() {
  return <section className="relative overflow-hidden bg-ink px-6 pb-24 pt-40 text-white md:px-12 lg:px-20 lg:pb-32"><div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_30%,rgba(108,71,255,.25),transparent_35%),radial-gradient(circle_at_22%_80%,rgba(0,212,255,.13),transparent_32%)]" /><div className="section-shell relative z-10 grid items-center gap-14 lg:grid-cols-[.9fr_1.1fr]"><Reveal><Badge accent="cyan">Product systems / 03</Badge><h1 className="mt-8 max-w-3xl font-display text-[clamp(3.6rem,8vw,7rem)] font-bold leading-[0.86] tracking-[-0.08em]">The suite is <span className="text-cyan">in orbit.</span></h1><p className="mt-8 max-w-xl text-lg leading-8 text-white/60">Three proprietary products shaped around real-world friction: care, commerce, and career momentum.</p><div className="mt-9 flex flex-wrap gap-3">{products.map((product) => <span className="rounded-full border border-white/15 px-4 py-3 text-[0.62rem] font-bold uppercase tracking-[0.16em] text-white/70" key={product.slug}>{product.name}</span>)}</div></Reveal><Reveal className="relative min-h-[28rem] rounded-panel border border-white/10 bg-white/[0.04]" delay={0.12} y={0}><ProductViewer /><span className="absolute bottom-6 left-6 text-[0.56rem] font-mono uppercase tracking-[0.18em] text-white/45">drag to explore / product signal</span></Reveal></div></section>;
}

function FeatureOrbit({ activeIndex }: { activeIndex: number }) {
  const activeProduct = products[activeIndex];
  return <div className="relative h-full min-h-[30rem] overflow-hidden rounded-panel bg-ink p-6 text-white md:p-10"><div aria-hidden="true" className="absolute inset-0 bg-[radial-gradient(circle_at_60%_35%,rgba(108,71,255,.58),transparent_32%),radial-gradient(circle_at_26%_75%,rgba(0,212,255,.26),transparent_28%)]" /><motion.div animate={{ rotate: activeIndex % 2 === 0 ? 360 : -360 }} aria-hidden="true" className="absolute left-1/2 top-1/2 size-[min(66vw,34rem)] -translate-x-1/2 -translate-y-1/2 rounded-full border border-white/15" transition={{ duration: 36, repeat: Infinity, ease: "linear" }} /><motion.div animate={{ rotate: activeIndex % 2 === 0 ? -360 : 360, scale: [1, 1.04, 1] }} aria-hidden="true" className="absolute left-1/2 top-1/2 size-[min(50vw,26rem)] -translate-x-1/2 -translate-y-1/2 rounded-full border border-cyan/30 [transform:rotate(24deg)]" transition={{ duration: 24, repeat: Infinity, ease: "linear" }} /><motion.div animate={{ scale: [0.92, 1, 0.92], rotate: activeIndex * 18 }} aria-hidden="true" className="absolute left-1/2 top-1/2 size-[min(28vw,13rem)] -translate-x-1/2 -translate-y-1/2 rounded-full bg-gradient-to-br from-violet to-cyan shadow-[0_0_110px_rgba(108,71,255,.55)]" transition={{ duration: 5, repeat: Infinity, ease: "easeInOut" }} /><div className="relative z-10 flex h-full flex-col justify-between"><div className="flex items-center justify-between text-[0.56rem] font-mono uppercase tracking-[0.18em] text-white/45"><span>suite orbit / 0{activeIndex + 1}</span><span>signal / live</span></div><AnimatePresence mode="wait"><motion.div className="max-w-xs" initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -16 }} key={activeProduct.slug} transition={{ duration: 0.38, ease: [0.22, 1, 0.36, 1] }}><p className="text-[0.62rem] font-bold uppercase tracking-[0.24em] text-cyan">{activeProduct.category}</p><h3 className="mt-4 font-display text-4xl font-bold tracking-[-0.07em]">{activeProduct.name}</h3><p className="mt-4 text-sm leading-7 text-white/60">{activeProduct.features[0]}</p></motion.div></AnimatePresence><div className="flex items-end justify-between gap-4"><div className="flex gap-2">{products.map((product, index) => <span aria-label={`${product.name} feature ${index === activeIndex ? "active" : "inactive"}`} className={index === activeIndex ? "h-1.5 w-12 rounded-full bg-cyan" : "h-1.5 w-5 rounded-full bg-white/25"} key={product.slug} />)}</div><span className="text-[0.56rem] font-mono uppercase tracking-[0.18em] text-white/45">scroll-linked view</span></div></div></div>;
}

export function FeatureWalkthrough() {
  const ref = useRef<HTMLDivElement>(null);
  const [activeIndex, setActiveIndex] = useState(0);
  const { scrollYProgress } = useScroll({ target: ref, offset: ["start start", "end end"] });
  useMotionValueEvent(scrollYProgress, "change", (value) => setActiveIndex(Math.min(products.length - 1, Math.floor(value * products.length))));

  return <section className="bg-white px-6 py-28 md:px-12 lg:px-20 lg:py-40"><div className="section-shell"><div className="mb-14 max-w-2xl"><Badge>Feature walkthrough</Badge><h2 className="mt-6 font-display text-4xl font-bold tracking-[-0.07em] md:text-6xl">One orbit.<br /><span className="text-muted">Many useful views.</span></h2><p className="mt-6 max-w-lg leading-8 text-muted">Scroll through the suite and watch the visual system follow the product signal without losing the story.</p></div><div className="relative min-h-[260vh]" ref={ref}><div className="sticky top-20 flex min-h-[calc(100vh-5rem)] items-center"><div className="grid w-full items-center gap-12 lg:grid-cols-[.75fr_1.25fr]"><div className="space-y-10">{products.map((product, index) => <motion.article animate={{ opacity: activeIndex === index ? 1 : 0.3, x: activeIndex === index ? 0 : 10 }} className="border-l-2 pl-6" key={product.slug} style={{ borderColor: activeIndex === index ? (index === 1 ? "#00d4ff" : "#6c47ff") : "rgba(13,13,26,.1)" }} transition={{ duration: 0.35 }}><p className="text-[0.62rem] font-bold uppercase tracking-[0.28em] text-violet">0{index + 1} / {product.category}</p><h3 className="mt-4 font-display text-3xl font-bold tracking-[-0.06em]">{product.name}</h3><p className="mt-4 max-w-sm leading-7 text-muted">{product.description}</p><ul className="mt-5 space-y-2">{product.features.map((feature) => <li className="flex items-center gap-3 text-sm" key={feature}><span className="grid size-5 place-items-center rounded-full bg-surface text-violet"><Check aria-hidden="true" className="size-3" /></span>{feature}</li>)}</ul></motion.article>)}</div><div className="hidden h-[min(68vh,42rem)] lg:block"><FeatureOrbit activeIndex={activeIndex} /></div><div className="lg:hidden"><FeatureOrbit activeIndex={activeIndex} /></div></div></div></div></div></section>;
}

export function ProductComparison() {
  const rows = [{ label: "Best for", values: ["Connected care", "Business clarity", "Career momentum"] }, { label: "Core signal", values: ["Care links", "Live ledger", "Experience signal"] }, { label: "System type", values: ["Healthcare platform", "Ops platform", "Career builder"] }];
  return <section className="bg-surface px-6 py-28 md:px-12 lg:px-20 lg:py-36"><div className="section-shell"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><Badge accent="cyan">Compare the orbit</Badge><h2 className="mt-6 font-display text-4xl font-bold tracking-[-0.07em] md:text-6xl">Different friction.<br /><span className="text-muted">Same care.</span></h2></div><p className="max-w-sm leading-8 text-muted">The products change shape around the people and decisions they serve.</p></div><div className="mt-14 overflow-x-auto rounded-panel border border-ink/10 bg-white"><table className="min-w-[44rem] w-full border-collapse text-left"><thead><tr className="border-b border-ink/10"><th className="p-6 text-[0.62rem] uppercase tracking-[0.18em] text-muted">System</th>{products.map((product) => <th className="p-6 font-display text-2xl tracking-[-0.05em]" key={product.slug}>{product.name}</th>)}</tr></thead><tbody>{rows.map((row) => <tr className="border-b border-ink/10 last:border-0" key={row.label}><th className="p-6 text-[0.62rem] uppercase tracking-[0.18em] text-muted">{row.label}</th>{row.values.map((value, index) => <td className="p-6 text-sm text-muted" key={`${row.label}-${index}`}>{value}</td>)}</tr>)}</tbody></table></div></div></section>;
}

export function ProductCta() { return <section className="bg-gradient-to-r from-violet to-cyan px-6 py-24 md:px-12 lg:px-20"><div className="section-shell flex flex-col items-start justify-between gap-10 md:flex-row md:items-center"><div><p className="text-[0.62rem] font-bold uppercase tracking-[0.3em] text-white/70">Your next product signal</p><h2 className="mt-5 max-w-2xl font-display text-4xl font-bold leading-none tracking-[-0.07em] text-white md:text-6xl">Build the system people return to.</h2></div><Button href="/contact" variant="soft">Start a product conversation</Button></div></section>; }
