"use client";

import { ArrowUpRight, Linkedin, Mail, Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/Badge";
import { GlassPanel } from "@/components/ui/GlassPanel";
import { Reveal } from "@/components/ui/Reveal";
import { TiltCard } from "@/components/ui/TiltCard";
import { milestones, team, values } from "@/lib/site-data";

export function AboutMission() {
  return <section className="bg-white px-6 py-28 md:px-12 lg:px-20 lg:py-40"><div className="section-shell grid items-end gap-14 lg:grid-cols-[1.2fr_.8fr]"><Reveal><p className="text-[0.62rem] font-bold uppercase tracking-[0.34em] text-violet">A useful kind of ambition</p><h2 className="mt-7 max-w-4xl font-display text-[clamp(3rem,7vw,6.5rem)] font-bold leading-[0.86] tracking-[-0.08em]">The next thing should feel <span className="text-gradient">lighter.</span></h2></Reveal><Reveal delay={0.1}><p className="max-w-md text-base leading-8 text-muted">InnovateHive is a digital systems studio for people building beyond the obvious. We bring strategy, design, engineering, and growth into the same orbit.</p></Reveal></div></section>;
}

export function CompanyTimeline() {
  return <section className="bg-surface px-6 py-28 md:px-12 lg:px-20 lg:py-36"><div className="section-shell"><div className="mb-16 flex items-end justify-between gap-8"><div><Badge>How we move</Badge><h2 className="mt-6 font-display text-4xl font-bold tracking-[-0.07em] md:text-6xl">Momentum, in sequence.</h2></div><span className="hidden text-[0.62rem] font-mono uppercase tracking-[0.18em] text-muted md:block">scroll / orbit →</span></div><div className="scrollbar-hidden flex snap-x gap-6 overflow-x-auto pb-6 lg:gap-8">{milestones.map((milestone, index) => <Reveal className="min-w-[min(80vw,22rem)] snap-start lg:min-w-[22rem]" delay={index * 0.06} key={milestone.year}><article className="relative min-h-[23rem] overflow-hidden rounded-panel border border-ink/10 bg-white p-8"><p className="font-display text-7xl font-bold tracking-[-0.09em] text-violet/20">{milestone.year}</p><div className="absolute left-8 top-32 h-px w-20 bg-gradient-to-r from-violet to-cyan" /><h3 className="mt-20 font-display text-3xl font-bold leading-none tracking-[-0.06em]">{milestone.title}</h3><p className="mt-5 leading-7 text-muted">{milestone.description}</p><span className="absolute bottom-7 right-8 text-[0.62rem] font-mono uppercase tracking-[0.16em] text-muted">/ {String(index + 1).padStart(2, "0")}</span></article></Reveal>)}</div></div></section>;
}

export function TeamGrid() {
  return <section className="bg-white px-6 py-28 md:px-12 lg:px-20 lg:py-36"><div className="section-shell"><div className="mb-16 max-w-2xl"><Badge accent="cyan">The people layer</Badge><h2 className="mt-6 font-display text-4xl font-bold tracking-[-0.07em] md:text-6xl">Small orbit. Serious pull.</h2></div><div className="grid gap-6 md:grid-cols-3">{team.map((member, index) => <Reveal delay={index * 0.08} key={member.name}><TiltCard className="group min-h-[24rem] rounded-panel bg-ink p-8 text-white"><div className="flex items-start justify-between"><div className="grid size-16 place-items-center rounded-full bg-gradient-to-br from-violet to-cyan font-display text-xl font-bold">{member.initials}</div><span className="text-[0.62rem] font-mono uppercase tracking-[0.16em] text-white/45">/ 0{index + 1}</span></div><div className="mt-24"><p className="text-[0.62rem] font-bold uppercase tracking-[0.2em] text-cyan">{member.role}</p><h3 className="mt-3 font-display text-3xl font-bold tracking-[-0.06em]">{member.name}</h3><p className="mt-4 leading-7 text-white/55">{member.bio}</p></div><div className="mt-6 flex gap-2 opacity-70 transition group-hover:opacity-100 group-focus-within:opacity-100">{member.socials.map((social) => <a aria-label={`${member.name} ${social.label}`} className="grid size-9 place-items-center rounded-full border border-white/15 transition hover:border-cyan hover:text-cyan" href={social.href} key={social.label}>{social.label === "LinkedIn" ? <Linkedin aria-hidden="true" className="size-4" /> : social.label === "Email" ? <Mail aria-hidden="true" className="size-4" /> : <ArrowUpRight aria-hidden="true" className="size-4" />}</a>)}</div></TiltCard></Reveal>)}</div></div></section>;
}

export function ValuesGrid() {
  return <section className="bg-surface px-6 py-28 md:px-12 lg:px-20 lg:py-36"><div className="section-shell"><div className="mb-16 flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><Badge>Core values</Badge><h2 className="mt-6 max-w-xl font-display text-4xl font-bold tracking-[-0.07em] md:text-6xl">Good systems leave room for people.</h2></div><Sparkles aria-hidden="true" className="size-12 text-violet" /></div><div className="grid gap-5 md:grid-cols-2">{values.map((value, index) => <Reveal delay={index * 0.06} key={value.number}><GlassPanel className="group min-h-[13rem] p-8 transition hover:-translate-y-1 hover:border-violet/30"><div className="flex items-start justify-between"><span className={value.accent === "cyan" ? "text-[0.62rem] font-mono uppercase tracking-[0.18em] text-cyan" : value.accent === "ink" ? "text-[0.62rem] font-mono uppercase tracking-[0.18em] text-ink" : "text-[0.62rem] font-mono uppercase tracking-[0.18em] text-violet"}>{value.number}</span><span className="size-2 rounded-full bg-current opacity-50" /></div><h3 className="mt-12 font-display text-3xl font-bold tracking-[-0.06em]">{value.title}</h3><p className="mt-4 max-w-lg leading-7 text-muted">{value.description}</p></GlassPanel></Reveal>)}</div></div></section>;
}
