"use client";

import { ArrowUpRight } from "lucide-react";
import { AnimatePresence, motion } from "framer-motion";
import { useState } from "react";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { GlassPanel } from "@/components/ui/GlassPanel";
import { TiltCard } from "@/components/ui/TiltCard";
import { caseStudies, type CaseStudyCategory } from "@/lib/site-data";

const filters: Array<{ label: string; value: CaseStudyCategory }> = [{ label: "All", value: "all" }, { label: "Product", value: "product" }, { label: "Healthcare", value: "healthcare" }, { label: "Business ops", value: "business-ops" }, { label: "Career", value: "career" }, { label: "Growth", value: "growth" }];

export function CaseStudyGrid() {
  const [active, setActive] = useState<CaseStudyCategory>("all");
  const visible = active === "all" ? caseStudies : caseStudies.filter((study) => study.category === active);
  return <section className="bg-white px-6 py-28 md:px-12 lg:px-20 lg:py-36"><div className="section-shell"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><Badge accent="cyan">Filter the proof</Badge><h2 className="mt-6 font-display text-4xl font-bold tracking-[-0.07em] md:text-6xl">Proof in motion.</h2></div><div aria-label="Case study filters" className="flex flex-wrap gap-2" role="group">{filters.map((filter) => <button aria-pressed={active === filter.value} className={active === filter.value ? "rounded-full bg-ink px-4 py-2 text-[0.62rem] font-bold uppercase tracking-[0.14em] text-white" : "rounded-full border border-ink/10 px-4 py-2 text-[0.62rem] font-bold uppercase tracking-[0.14em] text-muted transition hover:border-violet hover:text-violet"} key={filter.value} onClick={() => setActive(filter.value)} type="button">{filter.label}</button>)}</div></div><motion.div layout className="mt-14 grid gap-5 md:grid-cols-2 lg:grid-cols-12"><AnimatePresence mode="popLayout">{visible.map((study, index) => <motion.div animate={{ opacity: 1, y: 0 }} className={index % 3 === 0 ? "lg:col-span-7" : "lg:col-span-5"} exit={{ opacity: 0, y: 16 }} initial={{ opacity: 0, y: 16 }} key={study.slug} layout transition={{ duration: 0.35 }}><TiltCard className="group h-full min-h-[25rem] rounded-panel bg-surface p-7 md:p-9"><div className={study.accent === "cyan" ? "absolute inset-0 bg-gradient-to-br from-cyan/15 to-transparent opacity-0 transition group-hover:opacity-100" : study.accent === "ink" ? "absolute inset-0 bg-gradient-to-br from-ink/10 to-transparent opacity-0 transition group-hover:opacity-100" : "absolute inset-0 bg-gradient-to-br from-violet/15 to-transparent opacity-0 transition group-hover:opacity-100"} /><div className="relative z-10 flex h-full flex-col"><div className="flex items-center justify-between"><span className="text-[0.62rem] font-mono uppercase tracking-[0.18em] text-muted">{study.year} / {study.category}</span><ArrowUpRight aria-hidden="true" className="size-5 text-violet transition group-hover:-translate-y-1 group-hover:translate-x-1" /></div><div className="mt-auto"><p className="text-[0.62rem] font-bold uppercase tracking-[0.2em] text-violet">{study.metric}</p><h3 className="mt-3 max-w-xl font-display text-4xl font-bold leading-[0.92] tracking-[-0.07em]">{study.title}</h3><p className="mt-5 max-w-lg leading-7 text-muted">{study.summary}</p><div className="mt-6 flex flex-wrap gap-2">{study.tags.map((tag) => <span className="rounded-full border border-ink/10 px-3 py-2 text-[0.56rem] uppercase tracking-[0.14em] text-muted" key={tag}>{tag}</span>)}</div></div></div></TiltCard></motion.div>)}</AnimatePresence></motion.div>{visible.length === 0 ? <p className="mt-14 text-muted">The next proof is still forming. Try another orbit.</p> : null}</div></section>;
}

export function PortfolioCta() { return <section className="bg-surface px-6 pb-32 pt-0 md:px-12 lg:px-20"><div className="section-shell"><GlassPanel className="flex flex-col items-start justify-between gap-8 bg-ink p-8 text-white md:flex-row md:items-center md:p-12"><div><p className="text-[0.62rem] font-bold uppercase tracking-[0.25em] text-cyan">Your proof is next</p><h2 className="mt-4 max-w-2xl font-display text-4xl font-bold tracking-[-0.07em] md:text-5xl">Make the useful thing visible.</h2></div><Button href="/contact" variant="violet">Start a case study</Button></GlassPanel></div></section>; }
